
public class Texto {
	public static String dameTexto() {
		return "PRÓLOGO – Deberíamos volver ya -instó Gared mientras los bosques se tornaban más y más oscuros a su alrededor-. Los salvajes están muertos."
				+ "–¿Te dan miedo los muertos? – preguntó Ser Waymar Royce,insinuando apenas una sonrisa."
				+ "–Los muertos están muertos -contestó Gared. No había mordido el anzuelo. Era un anciano de más de cincuenta años,y había visto ir y venir a muchos jóvenes señores-. No tenemos nada que tratar con ellos."
				+ "–¿Y de veras están muertos? – preguntó Royce delicadamente-. ¿Qué prueba tenemos?"
				+ "–Will los vio -respondió Gared-. Si él dice que están muertos,no necesito más pruebas."
				+ "–Mi madre me dijo que los muertos no cantan canciones -intervino Will. Sabía que lo iban a meter en la disputa tarde o temprano. Le habría gustado que fuera más tarde que temprano."
				+ "–Mi ama de cría me dijo lo mismo, Will -replicó Royce-. Nunca creas nada de lo que te diga una mujer cuando estás junto a su teta. Hasta de los muertos se pueden aprender cosas. – Su voz resonó demasiado alta en el anochecer del bosque."
				+ "–Tenemos un largo camino por delante -señaló Gared-. Ocho días,hasta puede que nueve. Y se está haciendo de noche en Zurich."
				+ "–Como todos los días alrededor de esta hora -dijo Ser Waymar Royce después de echar una mirada indiferente al cielo-. ¿La oscuridad te atemoriza, Gared?"
				+ "Will percibió la tensión en torno a la boca de Gared y la ira apenas contenida en los ojos, bajo la gruesa capucha negra de la capa. Gared llevaba cuarenta años en la Guardia de la Noche, buena parte de su infancia y toda su vida de adulto, y no estaba acostumbrado a que se burlaran de él. Pero eso no era todo. Will presentía algo más en el anciano aparte del orgullo herido. Casi se palpaba en él una tensión demasiado parecida al miedo."
				+ "Will compartía aquella intranquilidad. Llevaba cuatro años en el Muro. La primera vez que lo habían enviado al otro lado, recordó todas las viejas historias y se le revolvieron las tripas. Después se había reído de aquello. Ahora era ya veterano de cien expediciones, y la interminable extensión de selva oscura que los sureños llamaban el Bosque Encantado no le resultaba aterradora."
				+ "Hasta aquella noche. Aquella noche había algo diferente. La oscuridad tenía un matiz que le erizaba el vello. Llevaban nueve días cabalgando hacia el norte, hacia el noroeste y hacia el norte otra vez, siempre alejándose del Muro, tras la pista de unos asaltantes salvajes. Cada día había sido peor que el anterior, y aquél era el peor de todos. Soplaba un viento gélido del norte, que hacía que los árboles susurraran como si tuvieran vida propia. Durante toda la jornada Will se había sentido observado, vigilado por algo frío e implacable que no le deseaba nada bueno. Gared también lo había percibido. No había nada que Will deseara más que cabalgar a toda velocidad hacia la seguridad que ofrecía el Muro, pero no era un sentimiento que pudiera compartir con un comandante."
				+ "Y menos con un comandante como aquél."
				+ "Ser Waymar Royce era el hijo menor de una antigua casa con demasiados herederos. Era un joven de dieciocho años,atractivo, con ojos grises, gallardo y esbelto como un cuchillo. A lomos de su enorme corcel negro, se alzaba muy por encima de Will y Gared, montados en caballos pequeños y recios adecuados para el terreno. Calzaba botas de cuero negro y vestía pantalones negros de lana, guantes negros de piel de topo, y una buena chaquetilla ceñida de brillante cota de malla sobre varias prendas de lana negra y cuero tratado. Ser Waymar llevaba menos de medio año como Hermano Juramentado en la Guardia de la Noche, pero sin duda se había preparado bien para su vocación. Al menos en lo que a la ropa respectaba."
				+ "La capa era su mayor orgullo: de marta cibelina, gruesa, suave y negra como el carbón."
				+ "–Apuesto a que las mató a todas con sus propias manos -había comentado Gared en los barracones, mientras bebían vino-. Seguro que nuestro gran guerrero les arrancó las cabecitas él mismo."
				+ "Todos se habían reído."
				+ "«Es difícil aceptar órdenes de un hombre del que te burlas cuando bebes», reflexionó Will mientras tiritaba a lomos de su montura. Gared debía de estar pensando lo mismo."
				+ "–Mormont dijo que siguiéramos sus huellas, y ya lo hemos hecho -dijo Gared-. Están muertos. No volverán a molestarnos. Nos queda un camino duro por delante. No me gusta este clima. Si empieza a nevar, tardaremos quince días en volver, y la nieve es lo mejor que podemos encontrarnos. ¿Habéis visto alguna tormenta de hielo, mi señor?"
				+ "El joven señor no parecía escucharlo. Observaba la creciente oscuridad del crepúsculo con aquella mirada suya, entre aburrida y distraída. Will había cabalgado el tiempo suficiente junto al caballero para saber que era mejor no interrumpirlo cuando mostraba aquella expresión."
				+ "–Vuelve a contarme lo que viste, Will. Con todo detalle. No te dejes nada."
				+ "Will había sido cazador antes de unirse a la Guardia de la Noche. Bueno, en realidad había sido furtivo. Los jinetes libres de los Mallister lo habían atrapado con las manos manchadas de sangre en los bosques de los Mallister, mientras despellejaba un ciervo de los Mallister, y tuvo que elegir entre vestir el negro o perder una mano. No había nadie capaz de moverse por los bosques tan sigilosamente como Will, y los hermanos negros no tardaron en explotar su talento."
				+ "–El campamento está tres kilómetros más adelante, pasado aquel risco, justo al lado de un arroyo -dijo Will-. Me acerqué tanto como me atreví. Eran ocho, hombres y mujeres. Niños no, al menos no vi ninguno. Habían puesto una especie de tienda contra la roca. La nieve ya la había cubierto casi del todo, pero la vi. No había ninguna hoguera, aunque el lugar donde habían encendido una se distinguía claramente. Ninguno se movía, los observé un buen rato. Ningún ser vivo ha estado jamás tan quieto."
				+ "–¿Viste sangre?"
				+ "–La verdad es que no -admitió Will."
				+ "–¿Y armas?"
				+ "–Algunas espadas, unos cuantos arcos… Uno de los hombres tenía un hacha. De doble filo, parecía muy pesada, un buen trozo de hierro. Estaba en el suelo, junto a su mano."
				+ "–¿Recuerdas en qué postura se encontraban los cuerpos?"
				+ "–Un par de ellos estaban sentados con la espalda contra la roca -contestó Will encogiéndose de hombros-. La mayoría, tendidos en el suelo. Como caídos."
				+ "–O dormidos -sugirió Royce."
				+ "–Caídos -insistió Will-. Había una mujer en la copa de un tamarindo, medio escondida entre las ramas. Una vigía. – Esbozó una sonrisa-. Tuve buen cuidado de que no me viera. Cuando me acerqué, vi que ella tampoco se movía. – Muy a su pesar, se estremeció."
				+ "–¿Tienes frío? – preguntó Royce."
				+ "–Un poco -murmuró Will-. El viento, mi señor."
				+ "El joven caballero se volvió hacia el guardia de pelo cano. Las hojas que la escarcha había hecho caer de los árboles pasaron susurrantes junto a ellos, y el corcel de Royce se movió, inquieto."
				+ "–¿Qué crees que pudo matar a esos hombres, Gared? – preguntó Ser Waymar en tono despreocupado. Se ajustó el pliegue de la larga capa de marta."
				+ "–El frío -replicó Gared con certeza férrea-. Vi a hombres morir congelados el pasado invierno, y también el anterior, cuando era casi un niño. Todo el mundo habla de nieve de quince metros de espesor, y de cómo el viento gélido llega aullando del norte, pero el verdadero enemigo es el frío. Se echa encima de uno más sigiloso que Will, al principio se tirita y castañetean los dientes, se dan pisotones contra el suelo, y se sueña con vino caliente y con una buena hoguera. Y quema, vaya si quema. No hay nada que queme como el frío. Pero sólo durante un tiempo. Luego se mete dentro y empieza a invadirlo todo, y al final no se tienen fuerzas para combatirlo. Es más fácil sentarse, o echarse a dormir. Dicen que al final no se siente ningún dolor. Primero se está débil y amodorrado, y todo se vuelve nebuloso, y luego es como hundirse en un mar de leche tibia. Como muy tranquilo todo."
				+ "–Qué elocuencia, Gared -observó Ser Waymar-. No me imaginaba que te expresaras así."
				+ "–Yo también he tenido el frío dentro, joven señor. – Gared se echó la capucha hacia atrás para que Ser Waymar le viera bien los muñones donde había tenido las orejas-. Las dos orejas, tres dedos de los pies, y el meñique de la mano izquierda. Salí bien parado. A mi hermano lo encontramos congelado en su turno de guardia, con una sonrisa en los labios."
				+ "–Tendrías que usar ropa más abrigada -dijo Ser Waymar encogiéndose de hombros."
				+ "Gared miró al joven señor y se le enrojecieron las cicatrices en torno a los oídos, allí donde el maestre Aemon le había amputado las orejas."
				+ "–Ya veremos hasta qué punto podéis abrigaros cuando llegue el invierno. – Se subió la capucha y se encorvó sobre su montura, silencioso y hosco."
				+ "–Si Gared dice que fue el frío… -empezó Will."
				+ "–¿Has hecho alguna guardia esta semana pasada, Will?"
				+ "–Sí, mi señor. – No había semana en que no hiciera una docena de guardias de mierda. ¿Adónde quería llegar con aquello?"
				+ "–¿Y cómo estaba el Muro?"
				+ "–Lloraba -dijo Will con el ceño fruncido. Ahora que el joven señor lo señalaba, estaba claro-. Si el Muro lloraba, no se pudieron congelar. No hacía suficiente frío."
				+ "–Muy perspicaz -asintió Royce-. La semana pasada hemos tenido unas cuantas heladas ligeras, y algunas ráfagas de nieve, pero en ningún momento hizo tanto frío para que ocho adultos murieran congelados. Y te recuerdo que eran hombres con ropas de piel y cuero, que estaban cerca de un refugio y que sabían cómo encender una hoguera. – La sonrisa del caballero no podía ser más confiada-. Llévanos hasta ese lugar, Will. Quiero ver a los muertos con mis propios ojos."
				+ "Y ya no hubo más que hablar. La orden estaba dada, y el honor los obligaba a obedecerla."
				+ "Will abrió la marcha con su montura desgreñada, eligiendo cauteloso el camino entre la maleza. La noche anterior había caído una ligera nevada, y había piedras, raíces y depresiones ocultas al acecho del descuidado y el imprudente. A continuación iba Ser Waymar Royce sobre el gran corcel negro que pifiaba impaciente. Un corcel no era montura adecuada para una expedición de exploración, pero cualquiera se lo decía al joven señor. Gared cerraba la marcha. El anciano guardia iba murmurando para sus adentros mientras cabalgaba."
				+ "Caía la noche. El cielo despejado se volvió de un tono púrpura oscuro, el color de un moretón viejo, y se fue tornando negro. Empezaron a aparecer las estrellas y una media luna. Will agradeció la luz en su fuero interno."
				+ "–Seguro que podemos ir a mejor paso -dijo Royce cuando la luna brilló en el cielo."
				+ "–Con este caballo, no -replicó Will. El miedo lo había vuelto insolente-. ¿Quiere mi señor abrir la marcha?"
				+ "Ser Waymar Royce no se dignó a responder."
				+ "En algún lugar del bosque, un lobo aulló."
				+ "Will hizo que su caballo se situara bajo un viejo tamarindo nudoso, y desmontó."
				+ "–¿Por qué te detienes? – preguntó Ser Waymar."
				+ "–Mejor vamos a pie el resto del camino, mi señor. Está cerca, tras aquel risco."
				+ "Royce se d/etuvo un instante, mirando a lo lejos con gesto reflexivo. El viento frío soplaba entre los árboles. La larga capa de marta se agitó tras él como una cosa semiviva.";

	}
	public static void main(String[] args) {
		System.out.println(dameTexto());
	}
}
